import type { Translations } from "./translationModel";


export const TEXT: Translations = {
  BLOODSUGAR: "BLOODSUGAR",
  DELETE_ALL_LOGS: "DELETE_ALL_LOGS",
  FETCH_DATA: "FETCH_DATA",
  INSULIN: "INSULIN",
  MMOL_PER_LITER: "MMOL_PER_LITER",
  SEND_RANDOM_DATA: "SEND_RANDOM_DATA",
  TIMESTAMP: "TIMESTAMP",
  UNITS: "UNITS",
  WAITING_FOR_DATA: "WAITING_FOR_DATA",
  SAVE_BG: "SAVE_BG",
  SAVE_BOLUS: "SAVE_BOLUS"
};
